---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)

candy <- read_csv(here("clean_data/clean_candy.csv"), guess_max = 800000)
```
```{r}
# Quesiton 1

candy %>% 
  count(gender)


candy %>% 
  summarise(number_of_ratings = sum(!is.na(rating)))
  
```
```{r}
#Question 2

candy %>% 
  select(going_out, age) %>% 
  group_by(going_out) %>% 
  summarise(average_age = median(age, na.rm = TRUE))


```

```{r} 
# Question 3

candy %>% 
  group_by(rating, candy_type) %>% 
  summarise(number_ratings = n()) %>% 
  slice_max(number_ratings)

  

```


```{r}
# Quesiton 4

candy %>% 
  filter(rating == "DESPAIR") %>% 
  filter(candy_type == "starburst") %>% 
  summarise(number_of_ratings = n())
```

```{r}
# number ratings 

candy_by_numbers <- candy %>%
  mutate(
    rating = case_when(
      rating == "JOY"     ~ 1,
      rating == "MEH"     ~ 0,
      rating == "DESPAIR" ~ -1,
      TRUE                ~ as.numeric(rating)
    ))
  
  

```


```{r}
# Question 6

candy_by_numbers %>%
  filter(gender == "Male") %>% 
  group_by(candy_type) %>% 
  summarise(total_ratings = sum(rating, na.rm = TRUE)) %>% 
  ungroup() %>% 
  slice_max(total_ratings)


candy_by_numbers %>% 
  group_by(gender, candy_type) %>% 
  summarise(total_ratings = sum(rating, na.rm = TRUE)) %>% 
  slice_max(total_ratings)


```
```{r}
# Quesiton 7
candy_by_numbers %>% 
  group_by(source, candy_type) %>% 
  summarise(total_ratings = sum(rating, na.rm = TRUE)) %>% 
  slice_max(total_ratings)

```
```{r}
# Question 8
candy_by_numbers %>% 
  group_by(country, candy_type) %>% 
  summarise(total_ratings = sum(rating, na.rm = TRUE)) %>% 
  slice_max(total_ratings)
```

