---
title: "Decathalon_Analysis"
output: html_notebook
---

```{r}
library(here)
here()

decath_data <- read_csv(here("clean_data/decath_data.csv"))
```

```{r}
# Question 1, longest long jump

decath_data %>% 
  filter(event == "long_jump") %>% 
  slice_max(result, n = 1)
```

```{r}
# Question 2, average 100m time per competition

decath_data %>% 
  select(result, event, competition) %>% 
  group_by(competition) %>% 
  filter(event == "x100m") %>% 
  summarise(across(where(is.numeric), mean))

```

```{r}

# Question 3 highest point across both competitions

decath_data %>% 
  group_by(competitor, competition_points) %>% 
  summarise() %>% 
  summarise(across(where(is.numeric), sum)) %>% 
  slice_max(competition_points)
  

```

```{r}
# Question 4, top 3 shot put per comp

decath_data %>% 
  filter(event == "shot_put") %>% 
  group_by(competition) %>% 
  slice_max(result, n = 3)
  
```

```{r}
# Average points for 400m times

decath_data %>% 
  filter(event == "x400m") %>% 
  group_by(result <= 50) %>% 
  summarise(avg_points = mean(competition_points))
  
  
```


```{r}

```

